### ISSUE TITLE
errors that scripts and files are missing for npm run package and npm run dmg

### ISSUE THREAD

**Issue by freedomtrain** [alvesjtiago/clip2p#2]
I m try to do some dev and testing and when I run npm run rebuild I receive an error that there is not script.
Also have errors that scripts and files are missing for npm run package and npm run dmg.

Thanks so much for this amazing app

**Comment by alvesjtiago** [comment]
Thank you so much for the kind words @fredhampton 😊

The ```npm run rebuild``` is optional, I will remove it from the readme file for the time being.
Regarding packaging and creating the dmg, the dependencies were not included as dev dependencies, thanks for noticing that. I've already pushed changes that reflect that so please pull the latest version, run ```npm install``` and try again.

**Comment by alvesjtiago** [comment]
@fredhampton did you have a chance to try it?

I'm going to close the issue but if you still have trouble running and packaging the app just let me know.
